export const AUTH_LOGIN = 'AUTH_LOGIN';
export type AUTH_LOGIN = typeof AUTH_LOGIN;
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export type AUTH_LOGOUT = typeof AUTH_LOGOUT;
export type AUTH = AUTH_LOGOUT | AUTH_LOGIN;

export const SEARCH_SEARCH = 'SEARCH_SEARCH';
export type SEARCH_SEARCH = typeof SEARCH_SEARCH;
export const SEARCH_SETRESULT = 'SEARCH_SETRESULT';
export type SEARCH_SETRESULT = typeof SEARCH_SETRESULT;
export const SEARCH_FETCHUSERINFO = 'SEARCH_FETCHUSERINFO';
export type SEARCH_FETCHUSERINFO = typeof SEARCH_FETCHUSERINFO;
export const SEARCH_SETFETCHUSERINFO = 'SEARCH_SETFETCHUSERINFO';
export type SEARCH_SETFETCHUSERINFO = typeof SEARCH_SETFETCHUSERINFO;